inspirehep/modules/authors/views.py
# -*- coding: utf-8 -*-
#
# This file is part of INSPIRE.
# Copyright (C) 2014-2017 CERN.
#
# INSPIRE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INSPIRE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with INSPIRE. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

"""INSPIRE authors views."""

from __future__ import absolute_import, division, print_function

import copy
import os
import re

import requests
from flask import (
    abort,
    Blueprint,
    current_app,
    jsonify,
    render_template,
    request,
    url_for,
    redirect,
)
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_required, current_user
from werkzeug.datastructures import MultiDict

from invenio_db import db
from invenio_workflows import workflow_object_class, start, resume
from invenio_workflows_ui.api import WorkflowUIRecord

from inspire_dojson import marcxml2record
from inspire_utils.record import get_value
from inspirehep.modules.forms.form import DataExporter

from .forms import AuthorUpdateForm
from .permissions import holdingpen_author_permission
from .tasks import formdata_to_model


blueprint = Blueprint(
    'inspirehep_authors',
    __name__,
    url_prefix='/authors',
    template_folder='templates',
    static_folder='static',
)


def set_int_or_skip(mydict, key, myint):
    try:
        mydict[key] = int(myint)
    except ValueError:
        pass


def convert_for_form(data):
    """
    Convert author data model form field names.

    FIXME This might be better in a different file and as a dojson conversion
    """
    if "name" in data:
        data["full_name"] = data["name"].get("value")
        try:
            data["given_names"] = data["name"].get(
                "value").split(",")[1].strip()
        except IndexError:
            data["given_names"] = ""
        data["family_name"] = data["name"].get("value").split(",")[0].strip()
        data["display_name"] = data["name"].get("preferred_name")
    if "native_name" in data:
        data["native_name"] = data["native_name"][0]
    if "urls" in data:
        data["websites"] = []
        for url in data["urls"]:
            if not url.get('description'):
                data["websites"].append({"webpage": url["value"]})
            else:
                if url["description"].lower() == "twitter":
                    data["twitter_url"] = url["value"]
                elif url["description"].lower() == "blog":
                    data["blog_url"] = url["value"]
                elif url["description"].lower() == "linkedin":
                    data["linkedin_url"] = url["value"]
        del data["urls"]
    if 'arxiv_categories' in data:
        data['research_field'] = data['arxiv_categories']
    if "positions" in data:
        data["institution_history"] = []
        data["public_emails"] = []
        for position in data["positions"]:
            if not any(
                [
                    key in position for key in ('institution', '_rank',
                                                'start_year', 'end_year')
                ]
            ):
                if 'emails' in position:
                    for email in position['emails']:
                        data["public_emails"].append(
                            {
                                'email': email,
                                'original_email': email
                            }
                        )
                continue
            pos = {}
            pos["name"] = position.get("institution", {}).get("name")
            rank = position.get("_rank", "")
            if rank:
                pos["rank"] = rank
            set_int_or_skip(pos, "start_year", position.get("start_date", ""))
            set_int_or_skip(pos, "end_year", position.get("end_date", ""))
            pos["current"] = True if position.get("current") else False
            pos["old_emails"] = position.get("old_emails", [])
            if position.get("emails"):
                pos["emails"] = position['emails']
                for email in position['emails']:
                    data["public_emails"].append(
                        {
                            'email': email,
                            'original_email': email
                        }
                    )
            data["institution_history"].append(pos)
        data["institution_history"].reverse()
    if 'advisors' in data:
        advisors = data['advisors']
        data['advisors'] = []
        for advisor in advisors:
            adv = {}
            adv["name"] = advisor.get("name", "")
            adv["degree_type"] = advisor.get("degree_type", "")
            data["advisors"].append(adv)
    if "ids" in data:
        for id in data["ids"]:
            try:
                if id["schema"] == "ORCID":
                    data["orcid"] = id["value"]
                elif id["schema"] == "INSPIRE BAI":
                    data["bai"] = id["value"]
                elif id["schema"] == "INSPIRE ID":
                    data["inspireid"] = id["value"]
            except KeyError:
                # Protect against cases when there is no value in metadata
                pass


def get_inspire_url(data):
    """ Generate url for the user to go back to INSPIRE. """
    url = ""
    if "bai" in data and data["bai"]:
        url = "http://inspirehep.net/author/profile/" + data["bai"]
    elif "control_number" in data and data["control_number"]:
        url = "http://inspirehep.net/record/" + str(data["control_number"])
    else:
        url = "http://inspirehep.net/hepnames"
    return url


@blueprint.route('/validate', methods=['POST'])
def validate():
    """Validate form and return validation errors.

    FIXME: move to forms module as a generic /validate where we can pass
    the for class to validate.
    """
    if request.method != 'POST':
        abort(400)

    is_update = True if request.args.get('is_update') == 'True' else False
    data = request.json or MultiDict({})
    formdata = MultiDict(data or {})
    form = AuthorUpdateForm(formdata=formdata, is_update=is_update)
    form.validate()

    result = {}
    changed_msgs = dict(
        (name, messages) for name, messages in form.messages.items()
        if name in formdata.keys()
    )
    result['messages'] = changed_msgs

    return jsonify(result)


@blueprint.route('/new', methods=['GET'])
@register_breadcrumb(blueprint, '.new', 'New author information')
@login_required
def new():
    """View for INSPIRE author new form."""
    data = {}
    bai = request.values.get('bai', u"", type=unicode)
    if bai:
        # Add BAI information to form in order to keep connection between
        # a HEPName and an author profile.
        data["bai"] = bai

    form = AuthorUpdateForm(data=data)

    ctx = {
        "action": url_for('.submitnew'),
        "name": "authorUpdateForm",
        "id": "authorUpdateForm",
    }

    return render_template('authors/forms/new_form.html', form=form, **ctx)


@blueprint.route('/<int:recid>/update', methods=['GET'])
@register_breadcrumb(blueprint, '.update', 'Update author information')
@login_required
def update(recid):
    """View for INSPIRE author update form."""
    data = {}
    if recid:
        try:
            url = os.path.join(
                current_app.config["AUTHORS_UPDATE_BASE_URL"],
                "record", str(recid), "export", "xm")
            xml = requests.get(url)
            record_regex = re.compile(
                r"\<record\>.*\<\/record\>", re.MULTILINE + re.DOTALL)
            xml_content = record_regex.search(xml.content).group()
            data = marcxml2record(xml_content)
            convert_for_form(data)
        except requests.exceptions.RequestException:
            pass
        data["control_number"] = recid
    else:
        return redirect(url_for("inspirehep_authors.new"))
    form = AuthorUpdateForm(data=data, is_update=True)
    ctx = {
        "action": url_for('.submitupdate'),
        "name": "authorUpdateForm",
        "id": "authorUpdateForm",
    }

    return render_template('authors/forms/update_form.html', form=form, **ctx)


@blueprint.route('/update/submit', methods=['POST'])
@login_required
def submitupdate():
    """Form action handler for INSPIRE author update form."""
    form = AuthorUpdateForm(formdata=request.form, is_update=True)
    visitor = DataExporter()
    visitor.visit(form)

    workflow_object = workflow_object_class.create(
        data={},
        id_user=current_user.get_id(),
        data_type="authors"
    )

    workflow_object.extra_data['formdata'] = copy.deepcopy(visitor.data)
    workflow_object.extra_data['is-update'] = True
    workflow_object.data = formdata_to_model(workflow_object, visitor.data)
    workflow_object.save()
    db.session.commit()

    # Start workflow. delay will execute the workflow in the background
    start.delay("author", object_id=workflow_object.id)

    ctx = {
        "inspire_url": get_inspire_url(visitor.data)
    }

    return render_template('authors/forms/update_success.html', **ctx)


@blueprint.route('/new/submit', methods=['POST'])
@login_required
def submitnew():
    """Form action handler for INSPIRE author new form."""
    form = AuthorUpdateForm(formdata=request.form)
    visitor = DataExporter()
    visitor.visit(form)

inspirehep/modules/authors/templates/authors/forms/new_form.html
{#
## This file is part of INSPIRE.
## Copyright (C) 2015 CERN.
##
## INSPIRE is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## INSPIRE is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with INSPIRE; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- extends "authors/forms/update_form.html" -%}
{% set new = True %}

{% block form_title scoped %}
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 vcenter">
      <h1>New author information</h1>
    </div>
  </div>
  <div class="well">
  This form allows you to add new author information. All modifications are transferred to <a href="http://inspirehep.net/hepnames" target="_blank">http://inspirehep.net/hepnames</a> upon approval.
  </div>
{% endblock form_title %}

inspirehep/modules/authors/templates/authors/forms/new_review_accepted.html
{#
## This file is part of INSPIRE.
## Copyright (C) 2015 CERN.
##
## INSPIRE is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## INSPIRE is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with INSPIRE; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- extends config.BASE_TEMPLATE -%}

{% block body %}

<div class="alert alert-success alert-form-success">
  <strong>The author update has been{% if approved %} approved {% else %} rejected {% endif %}<br></strong><br><a href="{{url_for('invenio_workflows_ui.details', objectid=request.args.get('objectid'))}}">Go back to the Holding Pen record.</a>
</div>
{% endblock body %}

inspirehep/modules/authors/templates/authors/forms/new_success.html
{#
## This file is part of INSPIRE.
## Copyright (C) 2015 CERN.
##
## INSPIRE is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## INSPIRE is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with INSPIRE; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- extends config.BASE_TEMPLATE -%}

{% block body %}
<div class="alert alert-success alert-form-success">
  <strong>Thank you for adding new profile information!<br></strong><br>The INSPIRE staff will review it and keep you informed.<br>
  {% if inspire_url %}
    <br><a href="{{inspire_url}}">Go back to INSPIRE</a>
  {% endif %}
</div>
{% endblock body %}

inspirehep/modules/authors/templates/authors/forms/review_form.html
{#
## This file is part of INSPIRE.
## Copyright (C) 2015 CERN.
##
## INSPIRE is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## INSPIRE is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with INSPIRE; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- extends "forms/form.html" -%}

{% block form_title scoped %}
  <div class="row">
    <div class="col-md-12">
      <h1>Reviewing author information</h1>
    </div>
  </div>
  <div class="well">
  Below you can find the information submitted by the user. After review/edit, click on Approve to send those changes to http://inspirehep.net.
  </div>
{% endblock form_title %}

{% block form_footer %}
  <div class="well action-bar">
  <a class="btn btn-danger pull-left" href="{{ url_for('inspirehep_authors.holdingpenreview', approved=False, objectid=objectid) }}"><i class="fa fa-trash-o fa-lg"></i> {{ _('Reject') }}</a>
  <span class="pull-right">
    <a href="#" title="{{_('Press Approve to finalize your review.')}}" class="btn btn-success form-submit" id="approve"><i class="fa fa-check-circle fa-lg"></i> {{ _('Approve') }}</a>
    <a href="#" title="{{_('Press to approve and create a curation ticket.')}}" class="btn btn-warning form-submit" id="approvecurate"><i class="fa fa-plus-circle fa-lg"></i> {{ _('Approve + curate') }}</a>
  </span>
  <span class="clearfix"></span>
</div>
{% endblock form_footer %}

{% block javascript %}

{{ super() }}

<script type="text/javascript">
require(
  [
    "jquery",
    "js/forms/inspire-form",
  ],

  function(
    $,
    InspireForm
  ) {

    $(function() {

    var config = {
      form: {
        save_url: '{{ url_for("inspirehep_authors.validate") }}',
        save_all_url: '{{ url_for("inspirehep_authors.validate", all='1') }}',
        complete_url: '{{ url_for("inspirehep_authors.validate", submit='1') }}',
        datepicker_element: '.datepicker',
        datepicker_options: {
            format: "YYYY",
            viewMode: 'years',
        },
        // Selectors
        datepickerSelector: '.datepicker',
        formSelector: '#authorUpdateForm',
        formDialogSelector: '#form-submit-dialog',

        // Classes
        formSaveClass: '.form-save',
        formSubmitClass: '', // avoid form submission
        dynamicFieldListClass : ".dynamic-field-list",
        uploaderSelector: "#uploader"
      }
    };

    // Initialize form
    InspireForm.attachTo("#authorUpdateForm", config.form);

    $("#approve").on("click", function() {
      $('#authorUpdateForm').append("<input type='hidden' name='ticket' value='False'/>");
      $('#authorUpdateForm').submit();
    });
    $("#approvecurate").on("click", function() {
      $('#authorUpdateForm').append("<input type='hidden' name='ticket' value='True'/>");
      $('#authorUpdateForm').submit();
    });
  });
});
</script>
{% endblock javascript %}

{%- block css %}
  {{ super() }}
  {%- assets "inspirehep_author_update_css" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
  {%- endassets %}
{%- endblock css %}

inspirehep/modules/authors/templates/authors/forms/update_form.html
{#
## This file is part of INSPIRE.
## Copyright (C) 2015 CERN.
##
## INSPIRE is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## INSPIRE is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with INSPIRE; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- extends "forms/form.html" -%}
{% set title = "New author information - INSPIRE Labs" if new else "Update author information - INSPIRE Labs" %}
{% set is_update = False if new else True %}


{% block form_title scoped %}
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 vcenter">
      <h1>{{ form._title }}</h1>
    </div>
  </div>
  <div class="well">
  This form allows you to update author information. All modifications are transferred to <a href="http://inspirehep.net/hepnames" target="_blank">http://inspirehep.net/hepnames</a> after our staff has checked them.
  </div>
{% endblock form_title %}

{% block javascript %}
{{ super() }}

{%- assets "inspirehep_authors_update_form_js" %}
<script src="{{ ASSET_URL }}"></script>
{%- endassets %}

<script type="text/javascript">
require(
  [
    "jquery",
    "js/forms/inspire-form",
    "js/authors/authors_submission_form"
  ],

  function(
    $,
    InspireForm,
    AuthorUpdateForm
  ) {

    $(function() {

    var config = {
      form: {
        save_url: '{{ url_for("inspirehep_authors.validate", is_update=is_update) }}',
        save_all_url: '{{ url_for("inspirehep_authors.validate", all='1', is_update=is_update) }}',
        complete_url: '{{ url_for("inspirehep_authors.validate", submit='1', is_update=is_update) }}',
        datepicker_element: '.datepicker',
        datepicker_options: {
            useCurrent: false,
            format: "YYYY",
            viewMode: 'years',
        },
        // Selectors
        datepickerSelector: '.datepicker',
        formSelector: '#authorUpdateForm',
        formDialogSelector: '#form-submit-dialog',

        // Classes
        formSaveClass: '.form-save',
        formSubmitClass: '.form-submit',
        dynamicFieldListClass : ".dynamic-field-list",
        uploaderSelector: "#uploader"
      }
    };

    var form = new AuthorUpdateForm();
    // Initialize form
    InspireForm.attachTo("#authorUpdateForm", config.form);

  });
});
</script>
{% endblock javascript %}

{%- block css %}
  {{ super() }}
  {%- assets "inspirehep_author_update_css" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
  {%- endassets %}
{%- endblock css %}

inspirehep/modules/authors/templates/authors/forms/update_success.html
{#
## This file is part of INSPIRE.
## Copyright (C) 2015 CERN.
##
## INSPIRE is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## INSPIRE is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with INSPIRE; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}
{%- extends config.BASE_TEMPLATE -%}

{% block body %}
<div class="alert alert-success alert-form-success">
  <strong>Thank you for your update!<br></strong><br>The INSPIRE staff will review it and your changes will be added to INSPIRE.<br>
  {% if inspire_url %}
    <br><a href="{{inspire_url}}">Go back to INSPIRE</a>
  {% endif %}
</div>
{% endblock body %}